# Generated by Django 6.1 on 2026-08-21 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('total_records', models.PositiveIntegerField(default=0)),
                ('matched_records', models.PositiveIntegerField(default=0)),
                ('exception_records', models.PositiveIntegerField(default=0)),
                ('match_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('processing_time_ms', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='UPLOADED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReconciliationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('MATCHED', 'Matched'), ('EXCEPTION', 'Exception')], max_length=20)),
                ('exception_type', models.CharField(blank=True, choices=[('', 'None'), ('DUPLICATE', 'Duplicate'), ('MISSING_PAYMENT', 'Missing Payment'), ('MISSING_SETTLEMENT', 'Missing Settlement'), ('CALCULATION_MISMATCH', 'Calculation Mismatch'), ('AMOUNT_MISMATCH', 'Amount Mismatch'), ('STATUS_MISMATCH', 'Status Mismatch'), ('UNKNOWN', 'Unknown')], default='', max_length=40)),
                ('difference', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('requires_manual_review', models.BooleanField(default=False)),
                ('rule_version', models.CharField(default='v1', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(choices=[('PROCESSING_FEE', 'Processing Fee'), ('REFUND', 'Refund'), ('DUPLICATE', 'Duplicate'), ('STATUS_ISSUE', 'Status Issue'), ('MISSING_RECORD', 'Missing Record'), ('AMOUNT_DISCREPANCY', 'Amount Discrepancy'), ('UNKNOWN', 'Unknown')], max_length=50)),
                ('explanation', models.TextField()),
                ('confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('recommended_action', models.TextField(blank=True)),
                ('evidence_summary', models.JSONField(blank=True, default=dict)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('prompt_version', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reconciliation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis', to='core.reconciliationresult')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100)),
                ('order_id', models.CharField(max_length=100)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('refund', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('adjustment', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expected_settlement', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('actual_settlement', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('payment_status', models.CharField(max_length=30)),
                ('settlement_status', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.batch')),
            ],
        ),
        migrations.AddField(
            model_name='reconciliationresult',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation', to='core.transaction'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('BATCH_CREATED', 'Batch Created'), ('RECONCILIATION_STARTED', 'Reconciliation Started'), ('RECONCILIATION_COMPLETED', 'Reconciliation Completed'), ('AI_ANALYSIS_CREATED', 'AI Analysis Created'), ('MANUAL_REVIEW', 'Manual Review')], max_length=50)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core.batch')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core.transaction')),
            ],
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_id'], name='core_transa_transac_665709_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['order_id'], name='core_transa_order_i_5e5c0f_idx'),
        ),
    ]
