# Generated by Django 6.1 on 2026-09-02 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliationresult',
            name='resolution_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ESCALATED', 'Escalated')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='reconciliationresult',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reconciliationresult',
            name='resolved_by',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
